In [1]:
numb_list = []    #####bu dogrusu
with open('C:\\Users\\ASUS\\Desktop\\test1A.txt') as f:
    for item in f:
        numb_list.append([float(i) for i in item.split()])
#print numb_list
print numb_list[0] 

[2.05252875014719, -1.4055424547272883, 3.768807443276579, 47.0711984235675, 52.733305265769964, 87.08321477151786, 89.25300109195898, 146.2950032296626, 159.08047879142845, 245.5093304980211, 317.80454893090985, 334.65564148375785, -166.26253960296404, -253.42338958577568, -220.10806805107438, -380.9995335490128, 185.0, -190.0, 6.816451061752502, 0.6233018250408124, 0.993012372127334, 0.5467160251017645, 2.318722837167989, 5.38071969580163, 7.717155783322803, 13.276037691965605, -0.33809635472550487, 2.822020822067355, 13.512822194247958, -305.89189968731614, 73.38456988243928, 99.33781614337617, 95.75587665428323, 148.3009968017727, 206.26258767713387, 408.72099281033127, 204.44735395217805, 69.98531596634092, -253.00849431687055, -266.47208730940224, -314.7456006061735, -805.4131011485528, 169.0, -254.0, -52.444715645594336, 0.749902489002664, 1.0237715870117663, 0.2462380817972296, 3.22436710918272, 6.139586702421205, 8.354007116743109, 29.36683070865843, -0.6411796100693969, -7.92

In [2]:
import pywt
import numpy as np
numb_list= np.reshape(numb_list, (100, 26))

In [3]:
import random 
#numb_list_train=numb_list[:50][:]
#numb_list_test=numb_list[50:][:]
numb_list_train=random.sample(numb_list, 50)
numb_list_test=random.sample(numb_list, 50)
print(numb_list_train)
print(numb_list_test)
#mylist[5:]

[array([ 1.85260490e+00,  4.94607984e+00,  1.17851467e+00,  3.16681674e+02,
        4.47032264e+01,  6.24617982e+01,  6.66875965e+01,  1.08185706e+02,
        1.68237075e+02,  1.65268856e+02,  1.71739243e+02,  6.09099706e+02,
       -1.58210496e+02, -1.77336306e+02, -1.86772458e+02, -4.51285853e+01,
        1.77000000e+02, -8.50000000e+01,  5.63029046e+01,  6.85913575e-01,
        1.00972976e+00,  1.59822930e-01,  1.96583296e+00,  3.87098225e+00,
        5.76183042e+00,  2.89094610e+01]), array([   1.0581932 ,    6.1620126 ,   -6.05161094,   51.66303702,
         59.71021674,   68.53110432,   69.32792305,  100.53275521,
        274.03703035,  190.44612855,  153.72851513,  313.34848044,
       -207.2115723 , -244.86591054, -182.47345354, -179.81024805,
        184.        , -132.        ,    8.00292897,    0.84705129,
          1.00004601,    0.59501748,    2.62392826,    4.25094631,
          6.0117937 ,    9.76435196]), array([   1.20080986,    3.28141578,   -5.2756908 ,    2.93663058

In [4]:
len(numb_list_train)
len(numb_list_test)

50

In [5]:
#train
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
pca.fit(numb_list_train)

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [6]:
print(pca.explained_variance_ratio_) 
print(pca.singular_values_) 

[0.59794524 0.3006886  0.04081626 0.02000049 0.01475632]
[1951.84136577 1384.11536998  509.95331101  356.9719647   306.62168426]


In [7]:
numblisttrain_new=pca.transform(numb_list_train)
print(numblisttrain_new)

[[-5.16727114e+02 -3.34044230e+02 -6.94390898e+01 -4.38913956e+01
  -7.49411527e+00]
 [-1.37291782e+02 -2.34866227e+02  1.09715759e+02 -3.44628715e+01
  -8.19073022e+01]
 [-1.28189608e+02 -4.62287430e+01 -2.95943450e+01 -8.58354510e+00
  -1.69867720e+01]
 [-9.41247552e+01  2.23213078e+01  1.59358684e+02  3.72688975e+01
  -3.93327170e+01]
 [ 3.84174524e+02  4.92678064e+00 -4.84121248e+01 -2.17051317e+01
  -2.59655598e+01]
 [ 1.17546633e+02 -3.20689241e+02 -3.49657406e+01 -6.04271761e+01
  -4.27069514e+00]
 [-1.65173646e+02 -8.31752447e+00 -9.04332892e+00  4.24900807e+00
   4.00347899e+01]
 [-2.05626106e+02 -8.98056532e-01 -2.07946699e+01 -3.15000723e+01
   1.12451939e+01]
 [ 1.77151334e+01 -1.58174108e+02 -6.72548140e+01 -5.11607094e+01
   1.79832414e+01]
 [-1.57687111e+02  1.77444291e+02  2.81464590e+01  1.22493399e+01
  -3.53095497e+00]
 [-1.12607300e+00  3.21497986e+02 -4.35406111e+01  3.30695382e+01
  -6.67018065e+01]
 [ 6.31176629e+01  1.38441236e+02 -2.23887463e+01  3.34267165e+01

In [8]:
numblisttest_new=pca.transform(numb_list_test)
print(numblisttest_new)

[[-8.79448232e+01 -2.09270195e+02 -1.51413470e+01  4.59919076e+01
   4.82212371e+01]
 [-2.26621663e+02  1.32015427e+02  1.44479227e+01 -4.27427393e+01
  -1.06370996e+02]
 [ 1.38693824e+02  1.67838823e+02 -3.54889723e+01  8.16653677e+01
   6.52548781e+01]
 [-2.05626106e+02 -8.98056532e-01 -2.07946699e+01 -3.15000723e+01
   1.12451939e+01]
 [ 6.31176629e+01  1.38441236e+02 -2.23887463e+01  3.34267165e+01
  -4.94623868e+01]
 [-3.56196045e+02  3.66008350e+02 -2.04296489e+02 -1.28324176e+02
   1.16246495e+01]
 [ 8.24171953e+01  3.81024176e+01 -6.43565727e+01  1.17177689e+02
   6.57818139e+01]
 [-4.68897238e+01 -1.95666261e+02 -2.35889304e+01 -6.98896302e+00
  -4.00011080e+01]
 [ 1.16322675e+02  1.22684250e+02  4.50031442e+01 -4.56819619e+01
   1.30066252e+01]
 [-1.70296222e+02 -1.04837051e+02  7.12185895e+00 -2.60155207e+00
   2.23672336e+01]
 [-4.15112602e+02  4.54522966e+02 -4.49290834e+01  3.77820998e+01
   4.10396496e+00]
 [-1.05960436e+02 -2.10717686e+01  4.06386975e+01  9.54478282e+01

In [9]:
type(numblisttrain_new)

numpy.ndarray

In [10]:
numb_listE = []    #####bu dogrusu
with open('C:\\Users\\ASUS\\Desktop\\test1E.txt') as f:
    for item in f:
        numb_listE.append([float(i) for i in item.split()])
#print numb_list
print numb_listE[0] 

[5.676659749025409, 22.345252163430846, -29.426782792736862, 296.88143471953606, 769.5202755176192, 848.4563228316991, 1383.1097716758766, 1046.5645764031146, 2467.789540807943, 2122.762965247814, 3050.4916303577634, 2563.385616060831, -2201.330618147276, -2333.7795580219718, -3330.2753254953805, -2109.6311748997737, 1027.0, -1765.0, 47.10007322431047, 0.8223136619417516, 0.5986732064426444, 1.2655209874617694, 33.811699755333564, 52.43598212634829, 119.50952550715974, 93.97665631322037, 12.11737482943737, 6.704649467048394, -162.97371789295727, 308.9347089185097, 836.7520068529263, 833.1746604370528, 1381.6260652837436, 1233.8540110584852, 2626.4431950653116, 1977.9145605083013, 3075.7463032475325, 3259.919722590502, -2600.048948864728, -3065.4016702729195, -3338.9632305524715, -3968.6597006741026, 1364.0, -1816.0, 37.57188186477911, 0.9943625708089316, 0.5568500398672562, 1.2140022348554362, 36.768627295236065, 51.47536901234935, 120.18179689926016, 109.87905070317281, 32.07309181313

In [11]:
import pywt
import numpy as np
numb_listE= np.reshape(numb_listE, (100, 26))

In [12]:
#numb_listE_train=numb_listE[:50][:]
numb_listE_train=random.sample(numb_listE, 50)
numb_listE_test=random.sample(numb_listE, 50)
#numb_listE_test=numb_listE[50:][:]
print(numb_listE_train)
print(numb_listE_test)

[array([-1.90994420e+00,  1.00567534e+01,  1.65182313e+00,  9.81526224e+01,
        1.88470162e+02,  3.33961836e+02,  4.50989667e+02,  6.74889134e+02,
        7.72524477e+02,  1.04929666e+03,  1.32343535e+03,  2.31817741e+03,
       -5.91200379e+02, -8.21432555e+02, -1.11226207e+03, -1.81024231e+03,
        7.76000000e+02, -5.27000000e+02,  2.51232609e+00,  4.98741939e-01,
        6.80618363e-01,  6.80381420e-01,  8.28132871e+00,  2.06415839e+01,
        3.89598347e+01,  5.89148944e+01]), array([-2.97300565e+00,  4.92605036e+01, -1.12785143e+02, -1.37721589e+02,
        4.37099370e+02,  1.27323708e+03,  1.00526377e+03,  7.76635871e+02,
        9.51223313e+02,  2.55485375e+03,  1.82638496e+03,  4.18242358e+03,
       -8.47552612e+02, -2.46899597e+03, -1.97642162e+03, -9.88712221e+02,
        8.20000000e+02, -8.85000000e+02, -5.03649011e+01,  3.32316248e-01,
        1.22049840e+00,  2.02510103e+00,  1.92054880e+01,  7.87196995e+01,
        8.73864185e+01,  6.81378384e+01]), array([ 1.178

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
pca.fit(numb_listE_train)


PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [14]:
print(pca.explained_variance_ratio_) 
print(pca.singular_values_) 

[0.64510863 0.16444726 0.09544903 0.04176058 0.02135112]
[14916.84653551  7531.36875981  5737.81239179  3795.28022971
  2713.75673654]


In [15]:
numblistEtrain_new=pca.transform(numb_listE_train)
print(numblistEtrain_new)

[[-1.04263998e+03  3.59815780e+02 -1.13419960e+03 -2.12556382e+02
   5.27639225e-01]
 [ 8.89638951e+02 -2.08953872e+03 -1.71382597e+03 -6.04101329e+02
  -8.58823648e+02]
 [ 1.06916726e+03 -1.27627090e+03  9.63880696e+02  1.94696007e+02
   1.81094823e+02]
 [-1.39048346e+03  9.99165491e+02 -1.06603045e+03 -1.22458567e+01
   1.55682651e+02]
 [ 3.09715416e+02 -3.07584835e+02  8.57451392e+01  6.75335986e+02
   1.83986779e+02]
 [ 1.31269856e+03 -1.55925777e+03  1.57067674e+01  1.53754732e+02
  -5.51900102e+02]
 [-2.02102352e+03  7.83504238e+02 -2.17355651e+02  3.33275064e+02
   6.18552379e+01]
 [ 7.23797784e+02 -7.90932890e+02 -8.94093776e+02  1.57630000e+03
   9.04530455e+02]
 [ 2.50984597e+03 -2.57328014e+03 -5.41608317e+02  7.09001299e+02
  -7.68238568e+02]
 [-2.59900013e+03  4.65555840e+02 -1.52446480e+02  1.26709554e+02
  -2.63124533e+01]
 [ 3.13469873e+03 -7.41508009e+02 -1.11645193e+03 -1.31872108e+02
   1.09895159e+03]
 [-2.11594937e+03  2.26082102e+02 -1.26930503e+03  5.03809061e+01

In [16]:
numblistEtest_new=pca.transform(numb_listE_test)
print(numblistEtest_new)

[[ 9.57811321e+02 -4.26345198e+02 -4.60250309e+01 -1.01231790e+03
   5.43943414e+02]
 [ 3.26398041e+03  1.14517186e+02 -2.66251890e+02 -1.00349001e+03
   1.35724582e+02]
 [ 5.23464479e+03  2.77455890e+03 -4.25532822e+02  3.46236291e+02
  -2.95906012e+02]
 [ 3.20180284e+03 -7.12352632e+02  1.27152873e+03  9.72109148e+02
  -2.64754868e+02]
 [-3.08394589e+03  6.82167771e+02  7.43947995e+02  4.75222396e+02
   1.61853071e+02]
 [-2.09896412e+03  1.08498652e+03 -7.24512006e+01  2.93253597e+01
  -6.19578204e+01]
 [-9.52053647e+02  3.63464706e+02  2.29262438e+02  1.09956453e+02
   3.29700329e+02]
 [ 2.96803185e+03 -5.42537968e+02 -9.69122089e+02  1.00039383e+02
   8.46332924e+02]
 [-2.29956390e+03  2.94101951e+02  7.75877283e+01 -7.85041216e+01
  -3.30352211e+01]
 [ 5.46516680e+03 -7.68517497e+02 -2.91483748e+02 -1.74694185e+03
   5.28524107e+02]
 [-1.62581541e+03  9.55269671e+02 -2.30969847e+02 -3.32501708e+02
   1.84247796e+02]
 [-1.75465409e+03  8.81993682e+02 -1.56475041e+02 -1.13819930e+02

In [17]:
yeni_matrix_train=np.vstack((numblisttrain_new,numblistEtrain_new))

In [18]:
print(yeni_matrix_train[50][1])
print(numblistEtrain_new[0][1])

359.81577958066714
359.81577958066714


In [19]:
from sklearn import svm
y = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
     1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
clf = svm.SVC()
clf.fit(yeni_matrix_train, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
yeni_matrix_test=np.vstack((numblisttest_new,numblistEtest_new))
len(yeni_matrix_test)

100

In [21]:
import numpy as np
from sklearn.metrics import accuracy_score
#X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
#>>> y = np.array([1, 1, 2, 2])
from sklearn.svm import SVC
clf = SVC()
clf.fit(yeni_matrix_train, y) 
y_test =[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,
         1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
predicted=clf.predict(yeni_matrix_test)
print(predicted)
print(accuracy_score(y_test,predicted))

[0 1 1 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 0 0 0 1 1 0
 0 1 1 0 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.74
